### ISSUE TITLE
MODE +i with wrong message

### ISSUE THREAD

**Issue by paulasbia** [taiscremaschi/42_Irc#46]
## Context
When we change a group with +i (invite only), the message received by a client  trying to join is wrong

![image](https://github.com/user-attachments/assets/d8295923-d031-4ab4-8ddb-a6841d0b4076)

**Comment by Pac4games** [comment]
I am not sure if I understand what the issue is here. On my end, I performed the following tests, compared them to another IRC server, and got similar results.

![image](https://github.com/user-attachments/assets/0b616fdc-8901-454f-9a6a-e6bc05a3f2d3)

**Comment by Pac4games** [comment]
I have now understood the issue. Please refer to the following HexChat screenshot, as the issue becomes more visible:

![image](https://github.com/user-attachments/assets/eace94da-a98e-45a1-9c28-1b9ffa99ca74)

The error message says that the channel requires a keyword to join, which is not the case. Instead, the reason why the client on the left cannot join is because it's an invite only channel and it has not been invited.
It will be updated to display the proper message.
